client_src = \
  lwm2m_registration.c \
  lwm2m_bootstrap.c \
  lwm2m_security_object.c \
  lwm2m_client_core.c \
  lwm2m_acl_object.c \
  lwm2m_server_object.c \
  lwm2m_object_tree.c \
  lwm2m_static.c
