common_src = \
    lwm2m_list.c \
  	network_abstraction_contiki.c \
    lwm2m_debug.c \
    lwm2m_util.c \
    lwm2m_util_contiki.c \
    lwm2m_object_store.c \
    lwm2m_definition.c \
    lwm2m_attributes.c \
    lwm2m_tree_node.c \
    lwm2m_endpoints.c \
    lwm2m_result.c \
    lwm2m_types.c \
    lwm2m_bootstrap_config.c \
    coap_abstraction_erbium.c 


ifeq ($(TINYDTLS),)
	common_src += dtls_abstraction_dummy.c
else
	common_src += dtls_abstraction_tinydtls.c
endif
    
