set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER mipsel-openwrt-linux-uclibc-gcc)
set(CMAKE_CXX_COMPILER mipsel-openwrt-linux-uclibc-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
